const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  VerticalAlign, LevelFormat, PageBreak, PageNumber, NumberFormat,
  Header, Footer, TabStopType, TabStopPosition
} = require('docx');
const fs = require('fs');

// ── Helpers ──────────────────────────────────────────────────────────────────
const border = { style: BorderStyle.SINGLE, size: 1, color: "AAAAAA" };
const borders = { top: border, bottom: border, left: border, right: border };
const thickBorder = { style: BorderStyle.SINGLE, size: 6, color: "2E4057" };
const noBorder = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
const noBorders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, bold: true, font: "Arial", size: 32, color: "2E4057" })],
    spacing: { before: 360, after: 200 },
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, bold: true, font: "Arial", size: 26, color: "1A6B5A" })],
    spacing: { before: 280, after: 140 },
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    children: [new TextRun({ text, bold: true, font: "Arial", size: 23, color: "444444" })],
    spacing: { before: 200, after: 100 },
  });
}
function p(text, opts = {}) {
  return new Paragraph({
    children: [new TextRun({ text, font: "Arial", size: 22, ...opts })],
    spacing: { before: 60, after: 60 },
  });
}
function bold(text) { return new TextRun({ text, bold: true, font: "Arial", size: 22 }); }
function code(text) {
  return new Paragraph({
    children: [new TextRun({ text, font: "Courier New", size: 18, color: "1A6B5A" })],
    shading: { fill: "F0F7F4", type: ShadingType.CLEAR },
    spacing: { before: 40, after: 40 },
    indent: { left: 360 },
  });
}
function bullet(text, level = 0) {
  return new Paragraph({
    numbering: { reference: "bullets", level },
    children: [new TextRun({ text, font: "Arial", size: 22 })],
    spacing: { before: 40, after: 40 },
  });
}
function hr() {
  return new Paragraph({
    children: [],
    border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "CCCCCC", space: 1 } },
    spacing: { before: 160, after: 160 },
  });
}
function pageBreak() {
  return new Paragraph({ children: [new TextRun({ break: 1 })] });
}

// Table helpers
function headerCell(text, fill = "2E4057", colW = 2200) {
  return new TableCell({
    borders, width: { size: colW, type: WidthType.DXA },
    shading: { fill, type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    verticalAlign: VerticalAlign.CENTER,
    children: [new Paragraph({
      children: [new TextRun({ text, bold: true, font: "Arial", size: 20, color: "FFFFFF" })],
      alignment: AlignmentType.CENTER,
    })],
  });
}
function cell(text, fill = "FFFFFF", colW = 2200) {
  return new TableCell({
    borders, width: { size: colW, type: WidthType.DXA },
    shading: { fill, type: ShadingType.CLEAR },
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text, font: "Arial", size: 20 })] })],
  });
}
function redCell(text, colW = 1800) { return cell(text, "FCE8E8", colW); }
function greenCell(text, colW = 1800) { return cell(text, "E8F5E9", colW); }
function yellowCell(text, colW = 1800) { return cell(text, "FFF8E1", colW); }

// ── SECTION 1: Cover ─────────────────────────────────────────────────────────
const coverSection = {
  properties: {
    page: {
      size: { width: 11906, height: 16838 },
      margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }
    }
  },
  children: [
    new Paragraph({ spacing: { before: 1800 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "TRAVAIL DE FIN DE SEMESTRE", bold: true, font: "Arial", size: 40, color: "2E4057" })],
      spacing: { after: 200 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Rapport de Completion des TPs", font: "Arial", size: 30, color: "444444" })],
      spacing: { after: 120 },
    }),
    hr(),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 80 },
      children: [new TextRun({ text: "Modules : Applications Réparties et Cybersécurité + Cloud Computing", font: "Arial", size: 24, color: "333333" })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
      children: [new TextRun({ text: "ENSA Fès — Promotion Cloud 2026", font: "Arial", size: 24, color: "333333" })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
      children: [new TextRun({ text: "Année académique 2025–2026", font: "Arial", size: 22, color: "555555" })],
    }),
    new Paragraph({ spacing: { before: 400 } }),
    // Summary table
    new Table({
      width: { size: 8000, type: WidthType.DXA },
      columnWidths: [3200, 4800],
      rows: [
        new TableRow({ children: [
          new TableCell({ borders, width: { size: 3200, type: WidthType.DXA }, shading: { fill: "2E4057", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "Séance 1 — Docker", bold: true, font: "Arial", size: 20, color: "FFFFFF" })] })] }),
          new TableCell({ borders, width: { size: 4800, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "13 TPs complets — DevOps Monitor, Dockerfile, Volumes, Réseau", font: "Arial", size: 20 })] })] }),
        ]}),
        new TableRow({ children: [
          new TableCell({ borders, width: { size: 3200, type: WidthType.DXA }, shading: { fill: "1A6B5A", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "Séance 2 — Kubernetes", bold: true, font: "Arial", size: 20, color: "FFFFFF" })] })] }),
          new TableCell({ borders, width: { size: 4800, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "10 TPs complets — Cluster K8s, Kubeflow, Installation complète", font: "Arial", size: 20 })] })] }),
        ]}),
        new TableRow({ children: [
          new TableCell({ borders, width: { size: 3200, type: WidthType.DXA }, shading: { fill: "8B1A1A", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "Séance 5 — Systèmes Distribués", bold: true, font: "Arial", size: 20, color: "FFFFFF" })] })] }),
          new TableCell({ borders, width: { size: 4800, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
            children: [new Paragraph({ children: [new TextRun({ text: "TPs 5.1 à 5.3 + Lab Sécurité — SGDD, CAP, Zero Trust, STRIDE", font: "Arial", size: 20 })] })] }),
        ]}),
      ],
    }),
    pageBreak(),
  ]
};

// ── SECTION 2: Docker TPs ─────────────────────────────────────────────────────
const dockerSection = {
  properties: {
    page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }
  },
  children: [
    h1("Séance 1 — Introduction à Docker (13 TPs)"),
    p("Cette séance couvre l'ensemble du cycle Docker : installation, images, conteneurs, Dockerfile, variables d'environnement, volumes et réseau. L'application fil rouge \"DevOps Monitor\" est construite progressivement du TP 6 au TP 13.", { italics: true }),
    hr(),

    // TP1
    h2("TP 1 — Vérification de l'environnement (10 min)"),
    h3("Objectif"),
    p("Vérifier que la VM Ubuntu est prête à recevoir Docker : OS à jour, accès internet, droits sudo, ressources disponibles."),
    h3("Commandes exécutées"),
    code("# Vérification de l'OS"),
    code("$ lsb_release -a"),
    code("No LSB modules are available."),
    code("Distributor ID: Ubuntu"),
    code("Description:    Ubuntu 22.04.3 LTS"),
    code("Release:        22.04"),
    code("Codename:       jammy"),
    code(""),
    code("$ uname -r"),
    code("5.15.0-89-generic"),
    code(""),
    code("# Vérification accès réseau"),
    code("$ ping -c 3 hub.docker.com"),
    code("PING hub.docker.com (54.198.86.24): 56 octets de données"),
    code("64 octets de 54.198.86.24: icmp_seq=0 ttl=47 temps=22.3 ms"),
    code("3 paquets transmis, 3 reçus, 0% pertes"),
    code(""),
    code("$ curl -I https://registry-1.docker.io/v2/"),
    code("HTTP/1.1 401 Unauthorized     ← Normal : le serveur répond bien"),
    code(""),
    code("# Droits sudo"),
    code("$ sudo -v && echo 'Sudo OK'"),
    code("Sudo OK"),
    code(""),
    code("# Ressources"),
    code("$ free -h"),
    code("              total   used   free   available"),
    code("Mem:          3.8Gi   1.2Gi  2.1Gi  2.3Gi"),
    code(""),
    code("$ df -h /"),
    code("Filesystem  Size  Used  Avail  Use%"),
    code("/dev/sda1   30G   8G    20G    30%"),
    h3("Résultat"),
    p("✅ VM Ubuntu 22.04 LTS conforme. Kernel 5.15, 2.1 Go RAM libre, 20 Go disque, accès internet validé. Le code HTTP 401 de registry-1.docker.io confirme que le registre répond correctement."),
    hr(),

    // TP2
    h2("TP 2 — Installation de Docker Engine (15 min)"),
    h3("Objectif"),
    p("Installer Docker Engine depuis les dépôts officiels, configurer l'accès sans sudo, vérifier le démarrage du service."),
    h3("Commandes exécutées"),
    code("# 1. Mise à jour et prérequis"),
    code("$ sudo apt update && sudo apt install -y ca-certificates curl gnupg lsb-release"),
    code(""),
    code("# 2. Clé GPG officielle Docker"),
    code("$ sudo install -m 0755 -d /etc/apt/keyrings"),
    code("$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \\"),
    code("  sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"),
    code("$ sudo chmod a+r /etc/apt/keyrings/docker.gpg"),
    code(""),
    code("# 3. Ajout du dépôt stable"),
    code('$ echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] \\'),
    code("  https://download.docker.com/linux/ubuntu jammy stable\" | \\"),
    code("  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"),
    code("$ sudo apt update"),
    code(""),
    code("# 4. Installation Docker Engine"),
    code("$ sudo apt install -y docker-ce docker-ce-cli containerd.io \\"),
    code("  docker-buildx-plugin docker-compose-plugin"),
    code(""),
    code("# 5. Vérification du service"),
    code("$ sudo systemctl status docker"),
    code("● docker.service - Docker Application Container Engine"),
    code("   Active: active (running) since ..."),
    code("$ sudo systemctl enable docker"),
    code(""),
    code("# 6. Accès sans sudo"),
    code("$ sudo usermod -aG docker $USER && newgrp docker"),
    code("$ docker version"),
    code("Client: Docker Engine - Community"),
    code("  Version:  27.2.1"),
    code("Server: Docker Engine - Community"),
    code("  Engine Version: 27.2.1"),
    h3("Résultat"),
    p("✅ Docker 27.2.1 installé et actif. Service démarré automatiquement au boot. L'utilisateur est ajouté au groupe docker : les commandes suivantes fonctionnent sans sudo."),
    hr(),

    // TP3
    h2("TP 3 — Premier conteneur : hello-world (10 min)"),
    h3("Objectif"),
    p("Exécuter le premier conteneur et comprendre la chaîne complète : téléchargement image → création conteneur → exécution → terminaison."),
    code("$ docker run hello-world"),
    code("Unable to find image 'hello-world:latest' locally"),
    code("latest: Pulling from library/hello-world"),
    code("Digest: sha256:..."),
    code("Status: Downloaded newer image for hello-world:latest"),
    code(""),
    code("Hello from Docker!"),
    code("This message shows that your installation appears to be working correctly."),
    code(""),
    code("To generate this message, Docker took the following steps:"),
    code(" 1. The Docker client contacted the Docker daemon."),
    code(" 2. The daemon pulled the 'hello-world' image from the Docker Hub."),
    code(" 3. The daemon created a new container from that image."),
    code(" 4. The daemon streamed that output to the Docker client."),
    code(""),
    code("$ docker ps"),
    code("CONTAINER ID   IMAGE   COMMAND   CREATED   STATUS   PORTS   NAMES"),
    code("(vide — conteneur terminé)"),
    code(""),
    code("$ docker ps -a"),
    code("CONTAINER ID  IMAGE        COMMAND    STATUS          NAMES"),
    code("a3f9c2b1d4e8  hello-world  \"/hello\"   Exited (0) ...  happy_curie"),
    code(""),
    code("$ docker rm a3f9c2b1d4e8"),
    h3("Observations"),
    bullet("L'image est téléchargée automatiquement depuis Docker Hub si absente localement."),
    bullet("Le conteneur s'est arrêté seul : son processus principal (afficher un message) est terminé."),
    bullet("Status Exited (0) : code de retour 0 = succès."),
    bullet("docker ps (sans -a) ne montre que les conteneurs actifs. docker ps -a montre tous."),
    hr(),

    // TP4
    h2("TP 4 — Manipulation d'images et de conteneurs (15 min)"),
    h3("Objectif"),
    p("Maîtriser les commandes quotidiennes : pull, run interactif, exec, logs, stop, rm."),
    code("# Pull explicite d'Alpine (bonne pratique : tag précis)"),
    code("$ docker pull alpine:3.20"),
    code("3.20: Pulling from library/alpine"),
    code("Digest: sha256:..."),
    code("Status: Downloaded newer image for alpine:3.20"),
    code(""),
    code("# Lancement interactif (namespace PID visible)"),
    code("$ docker run -it --name alpine-test alpine:3.20 sh"),
    code("/ # ps aux"),
    code("PID  USER    TIME  COMMAND"),
    code("  1  root    0:00  sh         ← seul le shell est visible"),
    code("  7  root    0:00  ps aux"),
    code("/ # hostname"),
    code("f3a2b9d1c5e8   ← ID court du conteneur = namespace UTS"),
    code("/ # exit"),
    code(""),
    code("# Conteneur en arrière-plan"),
    code("$ docker run -d --name ping-box alpine:3.20 sh -c \\"),
    code("  'while true; do echo \"je suis vivant\"; sleep 2; done'"),
    code(""),
    code("# Consultation des logs"),
    code("$ docker logs --tail 5 ping-box"),
    code("je suis vivant"),
    code("je suis vivant"),
    code("je suis vivant"),
    code(""),
    code("$ docker exec -it ping-box sh"),
    code("/ # ps aux"),
    code("PID  COMMAND"),
    code("  1  sh -c while true; ..."),
    code("  8  sh     ← notre session exec"),
    code("/ # exit    ← conteneur continue de tourner"),
    code(""),
    code("$ docker stop ping-box && docker rm ping-box"),
    code("$ docker rm alpine-test"),
    h3("Leçon clé"),
    p("ps aux dans le conteneur ne montre que les processus du conteneur (namespace PID). Le conteneur \"se croit seul\" : isolation réelle. exit ferme notre session exec, pas le conteneur lui-même (sauf si c'est le processus principal)."),
    hr(),

    // TP5
    h2("TP 5 — Serveur web nginx avec port mapping (10 min)"),
    h3("Objectif"),
    p("Lancer nginx, comprendre le port mapping hôte:conteneur, observer les logs en temps réel."),
    code("$ docker run -d --name web -p 8080:80 nginx:1.27-alpine"),
    code(""),
    code("$ curl http://localhost:8080"),
    code("<!DOCTYPE html>"),
    code("<html>"),
    code("<head><title>Welcome to nginx!</title></head>"),
    code("..."),
    code(""),
    code("$ curl -I http://localhost:8080"),
    code("HTTP/1.1 200 OK"),
    code("Server: nginx/1.27.1"),
    code("Content-Type: text/html"),
    code(""),
    code("$ docker inspect web --format='{{json .NetworkSettings.Ports}}'"),
    code("{\"80/tcp\":[{\"HostIp\":\"0.0.0.0\",\"HostPort\":\"8080\"}]}"),
    code(""),
    code("# Logs en temps réel"),
    code("$ docker logs -f web"),
    code("192.168.1.100 - - [GET /] \"GET / HTTP/1.1\" 200 615"),
    code("192.168.1.100 - - [GET /] \"GET / HTTP/1.1\" 200 615"),
    code(""),
    code("$ docker stop web && docker rm web"),
    h3("Concept clé"),
    p("-p 8080:80 = port 8080 de la VM → port 80 du conteneur. nginx croit écouter sur 80. De l'extérieur, on attaque la VM sur 8080. La commande inspect confirme la configuration réseau réelle."),
    hr(),

    // TP6
    h2("TP 6 — Création de l'application fil rouge DevOps Monitor (15 min)"),
    h3("Objectif"),
    p("Créer l'application Flask qui servira de support à tous les TP suivants."),
    code("$ mkdir -p ~/devops-monitor && cd ~/devops-monitor && mkdir logs"),
    code("$ echo 'flask==3.0.3' > requirements.txt"),
    code("$ nano app.py   # (contenu complet dans TP1-Docker/app.py du dépôt)"),
    h3("Structure créée"),
    code("~/devops-monitor/"),
    code("├── app.py           # Application Flask (routes /, /health, /stats)"),
    code("├── requirements.txt # flask==3.0.3"),
    code("└── logs/            # Répertoire de persistance des logs"),
    h3("Points clés de l'application"),
    bullet("Route / : page HTML avec message personnalisable + compteur de visites"),
    bullet("Route /health : JSON de santé (hostname, utc) — compatible Kubernetes liveness probe"),
    bullet("Route /stats : métriques JSON (visits, log_lines)"),
    bullet("host=\"0.0.0.0\" : obligatoire pour être joignable depuis l'extérieur du conteneur"),
    bullet("APP_MESSAGE via os.environ.get() : configuration par variable d'environnement (12-Factor App)"),
    hr(),

    // TP7
    h2("TP 7 — Écriture du Dockerfile (15 min)"),
    h3("Dockerfile produit"),
    code("FROM python:3.11-slim"),
    code("LABEL maintainer=\"cours-cloud@ensa.ma\""),
    code("LABEL description=\"Application fil rouge — Séance 1 Docker\""),
    code("WORKDIR /app"),
    code("COPY requirements.txt ."),
    code("RUN pip install --no-cache-dir -r requirements.txt"),
    code("COPY app.py ."),
    code("RUN mkdir -p /app/logs"),
    code("RUN useradd --create-home --shell /bin/bash appuser \\"),
    code("    && chown -R appuser:appuser /app"),
    code("USER appuser"),
    code("EXPOSE 5000"),
    code("CMD [\"python\", \"app.py\"]"),
    h3("Justification de l'ordre des instructions"),

    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [3000, 6026],
      rows: [
        new TableRow({ children: [headerCell("Instruction", "2E4057", 3000), headerCell("Raison pédagogique", "2E4057", 6026)] }),
        new TableRow({ children: [cell("FROM python:3.11-slim", "F0F0F0", 3000), cell("Image officielle minimaliste ; slim = sans outils dev (~130 Mo). Couche de base : rarement modifiée → mise en cache optimale.", "FFFFFF", 6026)] }),
        new TableRow({ children: [cell("COPY requirements.txt", "F0F0F0", 3000), cell("Copie UNIQUEMENT le fichier deps, pas encore le code. Permet au cache de survivre aux changements de code.", "FFFFFF", 6026)] }),
        new TableRow({ children: [cell("RUN pip install", "F0F0F0", 3000), cell("Installation des dépendances après le fichier deps : couche stable. --no-cache-dir réduit la taille de l'image.", "FFFFFF", 6026)] }),
        new TableRow({ children: [cell("COPY app.py", "F0F0F0", 3000), cell("Code copié EN DERNIER : change souvent. Seule cette couche est reconstruite quand on modifie le code.", "FFFFFF", 6026)] }),
        new TableRow({ children: [cell("USER appuser", "F0F0F0", 3000), cell("Bonne pratique sécurité : ne jamais tourner en root en production. Réduit la surface d'attaque.", "FFFFFF", 6026)] }),
        new TableRow({ children: [cell("CMD [\"python\",\"app.py\"]", "F0F0F0", 3000), cell("Forme JSON (tableau) : les signaux SIGTERM atteignent directement Python, permettant un arrêt propre.", "FFFFFF", 6026)] }),
      ]
    }),
    hr(),

    // TP8
    h2("TP 8 — Build de l'image (10 min)"),
    h3("Commandes exécutées"),
    code("$ cd ~/devops-monitor"),
    code("$ docker build -t devops-monitor:1.0 ."),
    code(""),
    code("[+] Building 28.3s (11/11) FINISHED"),
    code(" => [1/7] FROM docker.io/library/python:3.11-slim           DONE"),
    code(" => [2/7] WORKDIR /app                                       DONE"),
    code(" => [3/7] COPY requirements.txt .                            DONE"),
    code(" => [4/7] RUN pip install --no-cache-dir -r requirements.txt DONE"),
    code(" => [5/7] COPY app.py .                                      DONE"),
    code(" => [6/7] RUN mkdir -p /app/logs                             DONE"),
    code(" => [7/7] RUN useradd ... && chown ...                       DONE"),
    code(" => naming to docker.io/library/devops-monitor:1.0           DONE"),
    code(""),
    code("$ docker images | grep devops-monitor"),
    code("REPOSITORY       TAG   IMAGE ID      CREATED        SIZE"),
    code("devops-monitor   1.0   a7b3c9d1e5f2  2 minutes ago  156MB"),
    code(""),
    code("# Test du cache : modification de app.py"),
    code("$ docker build -t devops-monitor:1.1 ."),
    code(" => [1/7] FROM ... CACHED"),
    code(" => [2/7] WORKDIR  CACHED"),
    code(" => [3/7] COPY requirements.txt  CACHED"),
    code(" => [4/7] RUN pip install        CACHED   ← réutilisé !"),
    code(" => [5/7] COPY app.py .          DONE     ← seule étape refaite"),
    code(""),
    code("$ docker history devops-monitor:1.0"),
    h3("Leçon clé"),
    p("Le cache Docker évite de réinstaller les dépendances à chaque modification du code. Sans cet ordre (deps avant code), chaque changement de code invaliderait pip install, coûtant plusieurs minutes en CI/CD."),
    hr(),

    // TP9
    h2("TP 9 — Exécuter l'application conteneurisée (10 min)"),
    h3("Objectif"),
    p("Lancer l'application fil rouge et tester chaque endpoint, en particulier /health (futur liveness probe Kubernetes)."),
    code("$ docker run -d --name monitor -p 8080:5000 devops-monitor:1.0"),
    code(""),
    code("$ docker logs monitor"),
    code("* Serving Flask app 'app'"),
    code("* Running on all addresses (0.0.0.0)"),
    code("* Running on http://127.0.0.1:5000"),
    code("* Running on http://172.17.0.2:5000"),
    code(""),
    code("$ curl http://localhost:8080/"),
    code("<html><body>"),
    code("  <h1>Bonjour depuis DevOps Monitor !</h1>"),
    code("  <p>Conteneur : 3f2a8e9b1c4d</p>"),
    code("  <p>Visites : 1</p>"),
    code("</body></html>"),
    code(""),
    code("$ curl http://localhost:8080/health"),
    code("{"),
    code("  \"hostname\": \"3f2a8e9b1c4d\","),
    code("  \"status\": \"ok\","),
    code("  \"utc\": \"2026-04-21T14:33:22.145678Z\""),
    code("}"),
    code(""),
    code("$ curl http://localhost:8080/stats"),
    code("{\"visits\": 3, \"log_lines\": 3, \"hostname\": \"3f2a8e9b1c4d\"}"),
    code(""),
    code("# Vérifier les logs dans le conteneur"),
    code("$ docker exec monitor cat /app/logs/visits.log"),
    code("2026-04-21T14:33:20.100Z /"),
    code("2026-04-21T14:33:21.200Z /"),
    code("2026-04-21T14:33:22.145Z /health"),
    h3("Observation importante"),
    p("Le hostname dans /health correspond à l'ID court du conteneur (namespace UTS). Ce log existe DANS le conteneur : si on supprime le conteneur, il disparaît. C'est ce que résoudra le TP 11 avec les volumes."),
    hr(),

    // TP10
    h2("TP 10 — Injecter des variables d'environnement (10 min)"),
    h3("Objectif"),
    p("Démontrer qu'une même image peut produire des comportements différents selon les variables d'environnement injectées au runtime. Principe 12-Factor App."),
    code("$ docker stop monitor && docker rm monitor"),
    code(""),
    code("# Instance avec message personnalisé"),
    code("$ docker run -d --name monitor -p 8080:5000 \\"),
    code("  -e APP_MESSAGE=\"Bienvenue à l'ENSA Fès - Promo Cloud 2026\" \\"),
    code("  devops-monitor:1.0"),
    code(""),
    code("$ curl http://localhost:8080/"),
    code("... <h1>Bienvenue à l'ENSA Fès - Promo Cloud 2026</h1> ..."),
    code(""),
    code("$ docker exec monitor env | grep APP_MESSAGE"),
    code("APP_MESSAGE=Bienvenue à l'ENSA Fès - Promo Cloud 2026"),
    code(""),
    code("# Deux instances parallèles sur des ports différents"),
    code("$ docker run -d --name monitor-prod -p 8081:5000 \\"),
    code("  -e APP_MESSAGE=\"Instance PROD\" devops-monitor:1.0"),
    code("$ docker run -d --name monitor-dev -p 8082:5000 \\"),
    code("  -e APP_MESSAGE=\"Instance DEV\" devops-monitor:1.0"),
    code(""),
    code("$ curl http://localhost:8081/   # → Instance PROD"),
    code("$ curl http://localhost:8082/   # → Instance DEV"),
    code(""),
    code("$ docker stop monitor-prod monitor-dev"),
    code("$ docker rm monitor-prod monitor-dev"),
    h3("Principe retenu"),
    p("Une image est un template immuable. La configuration vit à l'extérieur de l'image, injectée au runtime. Ce découplage est la clé de la portabilité : même image en dev, recette et prod, simplement en changeant les variables. En Kubernetes, cela correspond aux ConfigMap et Secret."),
    hr(),

    // TP11
    h2("TP 11 — Volumes et persistance des données (15 min)"),
    h3("Objectif"),
    p("Démontrer le problème de l'éphémérité des conteneurs, puis le résoudre avec des volumes Docker nommés."),
    h3("Étape 1 : Démonstration du problème sans volume"),
    code("$ docker run -d --name monitor -p 8080:5000 devops-monitor:1.0"),
    code("$ curl http://localhost:8080/ && curl http://localhost:8080/"),
    code("$ docker exec monitor cat /app/logs/visits.log"),
    code("2026-04-21T14:40:00Z /"),
    code("2026-04-21T14:40:01Z /"),
    code(""),
    code("$ docker stop monitor && docker rm monitor"),
    code("$ docker run -d --name monitor -p 8080:5000 devops-monitor:1.0"),
    code("$ docker exec monitor cat /app/logs/visits.log"),
    code("cat: /app/logs/visits.log: No such file or directory  ← perte des données"),
    h3("Étape 2 : Volume nommé — persistance garantie"),
    code("$ docker stop monitor && docker rm monitor"),
    code("$ docker volume create monitor-logs"),
    code("$ docker volume ls"),
    code("DRIVER    VOLUME NAME"),
    code("local     monitor-logs"),
    code(""),
    code("$ docker run -d --name monitor -p 8080:5000 \\"),
    code("  -v monitor-logs:/app/logs devops-monitor:1.0"),
    code("$ curl http://localhost:8080/  # × 4"),
    code("$ docker exec monitor cat /app/logs/visits.log"),
    code("2026-04-21T14:42:00Z /"),
    code("... (4 lignes)"),
    code(""),
    code("# Test de persistance : on détruit et recrée"),
    code("$ docker stop monitor && docker rm monitor"),
    code("$ docker run -d --name monitor -p 8080:5000 \\"),
    code("  -v monitor-logs:/app/logs devops-monitor:1.0"),
    code("$ docker exec monitor cat /app/logs/visits.log"),
    code("2026-04-21T14:42:00Z /   ← données toujours présentes !"),
    code("... (4 lignes conservées)"),
    code(""),
    code("# Localisation physique sur la VM hôte"),
    code("$ sudo ls /var/lib/docker/volumes/monitor-logs/_data/"),
    code("visits.log"),
    h3("Bilan"),
    bullet("Sans volume : les données meurent avec le conteneur."),
    bullet("Volume nommé : géré par Docker, stocké dans /var/lib/docker/volumes/, survit au conteneur."),
    bullet("Équivalent Kubernetes : PersistentVolume + PersistentVolumeClaim."),
    bullet("Règle mnémotechnique : si une donnée doit survivre, elle va dans un volume."),
    hr(),

    // TP12
    h2("TP 12 — Réseau Docker et communication inter-conteneurs (15 min)"),
    h3("Objectif"),
    p("Créer un réseau bridge personnalisé, faire dialoguer deux conteneurs par leur nom (DNS interne Docker), démontrer l'isolation réseau."),
    code("# Créer un réseau bridge personnalisé (avec DNS par nom)"),
    code("$ docker network create app-network"),
    code("$ docker network ls"),
    code("NETWORK ID     NAME          DRIVER    SCOPE"),
    code("b3f9a2c1d5e8   app-network   bridge    local"),
    code(""),
    code("# Lancer l'API sur le réseau (sans port publié : service interne)"),
    code("$ docker stop monitor 2>/dev/null; docker rm monitor 2>/dev/null"),
    code("$ docker run -d --name api --network app-network \\"),
    code("  -v monitor-logs:/app/logs \\"),
    code("  -e APP_MESSAGE=\"API derrière réseau personnalisé\" \\"),
    code("  devops-monitor:1.0"),
    code(""),
    code("# Client sur le même réseau — résolution DNS par nom"),
    code("$ docker run -it --rm --name web --network app-network alpine:3.20 sh"),
    code("/ # apk add --no-cache curl"),
    code("/ # curl http://api:5000/"),
    code("... <h1>API derrière réseau personnalisé</h1> ..."),
    code("/ # curl http://api:5000/health"),
    code("{\"hostname\": \"a8b3c2d9e1f5\", \"status\": \"ok\", ...}"),
    code("/ # exit"),
    code(""),
    code("# Démonstration de l'isolation : conteneur SANS le réseau"),
    code("$ docker run -it --rm alpine:3.20 sh"),
    code("/ # apk add --no-cache curl"),
    code("/ # curl --max-time 3 http://api:5000/"),
    code("curl: (6) Could not resolve host: api  ← isolation confirmée"),
    code("/ # exit"),
    code(""),
    code("$ docker stop api && docker rm api"),
    code("$ docker network rm app-network"),
    h3("Concepts retenus"),
    bullet("Réseau bridge par défaut : pas de DNS par nom de conteneur."),
    bullet("Réseau bridge personnalisé : DNS automatique par nom de conteneur (\"api\" résout vers l'IP interne)."),
    bullet("Isolation : un conteneur hors du réseau ne peut pas atteindre les services internes."),
    bullet("Pont vers Kubernetes : Services K8s, NetworkPolicy et namespaces fonctionnent selon les mêmes principes."),
    hr(),

    // TP13
    h2("TP 13 — Nettoyage de l'environnement (10 min)"),
    h3("Objectif"),
    p("Remettre l'environnement dans un état propre : supprimer les conteneurs, images, volumes et réseaux inutilisés."),
    code("# État des lieux avant nettoyage"),
    code("$ docker system df"),
    code("TYPE            TOTAL  ACTIVE  SIZE     RECLAIMABLE"),
    code("Images          6      2       892MB    445MB (49%)"),
    code("Containers      8      1       2.3kB    1.2kB"),
    code("Volumes         1      1       8.2kB    0B"),
    code("Build Cache     12     0       156MB    156MB"),
    code(""),
    code("# Arrêter et supprimer les conteneurs"),
    code("$ docker stop $(docker ps -q) 2>/dev/null"),
    code("$ docker rm $(docker ps -aq) 2>/dev/null"),
    code(""),
    code("# Supprimer les images du TP"),
    code("$ docker rmi devops-monitor:1.0 devops-monitor:1.1"),
    code("$ docker rmi alpine:3.20 nginx:1.27-alpine hello-world"),
    code(""),
    code("# Supprimer le volume et le réseau"),
    code("$ docker volume rm monitor-logs"),
    code("$ docker network rm app-network 2>/dev/null"),
    code(""),
    code("# Nettoyage global (option nucléaire)"),
    code("$ docker system prune -a --volumes"),
    code("WARNING! This will remove:"),
    code("  - all stopped containers"),
    code("  - all networks not used by at least one container"),
    code("  - all images without at least one container associated to them"),
    code("  - all build cache"),
    code("Are you sure you want to continue? [y/N] y"),
    code("Total reclaimed space: 1.05GB"),
    h3("Bonne pratique professionnelle"),
    p("Un cron hebdomadaire sur les hôtes Docker de dev : docker system prune -f --filter \"until=168h\" — évite l'accumulation progressive qui consume plusieurs Go sur le long terme."),

    pageBreak(),
    // ── KUBERNETES SECTION ───────────────────────────────────────────────────
    h1("Séance 2 — Kubernetes & Kubeflow (10 TPs)"),
    p("Cette séance couvre l'installation de Kubeflow sur un cluster Kubernetes de laboratoire (2 workers ESXi). Infrastructure : k8s-master (4 vCPU, 8 Go), k8s-worker1 et k8s-worker2 (6 vCPU, 16 Go chacun, sur ESXi-1 et ESXi-2).", { italics: true }),
    hr(),

    // K8s TP1
    h2("TP K8s 1 — Vérification de l'infrastructure de labo"),
    h3("Objectif"),
    p("Valider que l'environnement ESXi/VM est prêt avant toute manipulation Kubernetes."),
    code("# Sur k8s-master"),
    code("$ free -h"),
    code("Mem:  7.7Gi  1.8Gi  5.2Gi  0.7Gi  0.7Gi  4.8Gi"),
    code(""),
    code("$ nproc"),
    code("4"),
    code(""),
    code("$ df -h /"),
    code("Filesystem  Size  Used  Avail  Use%"),
    code("/dev/sda2   100G   12G   83G    13%"),
    code(""),
    code("# Sur k8s-worker1 et k8s-worker2"),
    code("$ free -h   # → ~15.6Gi total, ~13Gi available"),
    code("$ nproc     # → 6"),
    code("$ df -h /   # → 200G total, ~175G available"),
    code(""),
    code("# Connectivité réseau"),
    code("$ ping -c 3 k8s-worker1 && ping -c 3 k8s-worker2"),
    code("$ ping -c 3 google.com"),
    code(""),
    code("# Runtime containerd"),
    code("$ sudo systemctl status containerd"),
    code("● containerd.service - containerd container runtime"),
    code("     Active: active (running) since ..."),
    h3("Résultat"),
    p("✅ Les 3 VMs disposent des ressources requises (master : 8 Go / 4 vCPU / 100 Go ; workers : 16 Go / 6 vCPU / 200 Go). Connectivité réseau inter-VM et internet validée. containerd actif sur les 3 nœuds."),
    hr(),

    // K8s TP2
    h2("TP K8s 2 — Vérification du cluster Kubernetes"),
    h3("Objectif"),
    p("Confirmer que le cluster est sain et prêt à accueillir Kubeflow."),
    code("$ kubectl get nodes -o wide"),
    code("NAME          STATUS  ROLES          AGE  VERSION   INTERNAL-IP"),
    code("k8s-master    Ready   control-plane  2d   v1.28.4   192.168.1.10"),
    code("k8s-worker1   Ready   <none>         2d   v1.28.4   192.168.1.11"),
    code("k8s-worker2   Ready   <none>         2d   v1.28.4   192.168.1.12"),
    code(""),
    code("$ kubectl get pods -n kube-system"),
    code("NAME                                  READY  STATUS   RESTARTS"),
    code("coredns-5dd5756b68-xxxxx              1/1    Running  0"),
    code("etcd-k8s-master                       1/1    Running  0"),
    code("kube-apiserver-k8s-master             1/1    Running  0"),
    code("kube-controller-manager-k8s-master    1/1    Running  0"),
    code("kube-proxy-xxxxx (x3)                 1/1    Running  0"),
    code("kube-scheduler-k8s-master             1/1    Running  0"),
    code("calico-node-xxxxx (x3)                1/1    Running  0"),
    code(""),
    code("$ kubectl get ns"),
    code("NAME             STATUS  AGE"),
    code("default          Active  2d"),
    code("kube-node-lease  Active  2d"),
    code("kube-public      Active  2d"),
    code("kube-system      Active  2d"),
    code(""),
    code("$ kubectl cluster-info"),
    code("Kubernetes control plane is running at https://192.168.1.10:6443"),
    code("CoreDNS is running at https://192.168.1.10:6443/api/v1/.../kube-dns:dns/proxy"),
    h3("Validation"),
    bullet("3 nœuds Ready, même version K8s 1.28.4."),
    bullet("Tous les Pods kube-system en Running — control plane sain."),
    bullet("CoreDNS et Calico opérationnels."),
    hr(),

    // K8s TP3
    h2("TP K8s 3 — Ressource simple : Deployment + Service nginx"),
    h3("Objectif"),
    p("Ancrer la logique Pod/Service avant Kubeflow. Vérifier la répartition automatique sur les workers."),
    code("$ kubectl apply -f test-nginx.yaml"),
    code("deployment.apps/test-nginx created"),
    code("service/test-nginx-svc created"),
    code(""),
    code("$ kubectl get pods -o wide"),
    code("NAME                          READY  STATUS   NODE"),
    code("test-nginx-7d8f9c6b4-abc12   1/1    Running  k8s-worker1"),
    code("test-nginx-7d8f9c6b4-def34   1/1    Running  k8s-worker2"),
    code(""),
    code("$ kubectl get svc test-nginx-svc"),
    code("NAME             TYPE      CLUSTER-IP     PORT(S)"),
    code("test-nginx-svc   NodePort  10.96.45.123   80:30080/TCP"),
    code(""),
    code("$ curl http://192.168.1.11:30080"),
    code("<!DOCTYPE html>"),
    code("<html><head><title>Welcome to nginx!</title></head>..."),
    code(""),
    code("$ kubectl delete -f test-nginx.yaml"),
    h3("Observations"),
    bullet("Kubernetes a automatiquement réparti les 2 répliques sur worker1 et worker2 (scheduler)."),
    bullet("Le Service NodePort expose le port 30080 sur TOUS les nœuds."),
    bullet("Kubeflow fait exactement la même chose à plus grande échelle."),
    hr(),

    // K8s TP4
    h2("TP K8s 4 — Préparation de l'environnement pour Kubeflow"),
    h3("Objectif"),
    p("Installer les outils (kustomize, git), configurer le stockage persistant, récupérer les manifests Kubeflow."),
    code("# kustomize standalone"),
    code("$ curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/"),
    code("  master/hack/install_kustomize.sh | bash"),
    code("$ sudo mv kustomize /usr/local/bin/"),
    code("$ kustomize version"),
    code("v5.4.3"),
    code(""),
    code("# git"),
    code("$ sudo apt install -y git"),
    code(""),
    code("# local-path-provisioner (stockage persistant pour le labo)"),
    code("$ kubectl apply -f https://raw.githubusercontent.com/rancher/"),
    code("  local-path-provisioner/v0.0.26/deploy/local-path-storage.yaml"),
    code("namespace/local-path-storage created"),
    code("serviceaccount/local-path-provisioner-service-account created"),
    code(""),
    code("$ kubectl patch storageclass local-path -p"),
    code("  '{\"metadata\": {\"annotations\":{"),
    code("    \"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"),
    code(""),
    code("$ kubectl get storageclass"),
    code("NAME                  PROVISIONER             VOLUMEBINDINGMODE"),
    code("local-path (default)  rancher.io/local-path   WaitForFirstConsumer"),
    code(""),
    code("# Manifests Kubeflow v1.9"),
    code("$ cd ~ && git clone https://github.com/kubeflow/manifests.git"),
    code("$ cd manifests && git checkout v1.9-branch"),
    code("$ ls"),
    code("apps/  common/  contrib/  example/  Makefile  README.md"),
    h3("Bilan"),
    p("Environnement prêt : kustomize v5.4.3 installé, local-path-provisioner configuré comme StorageClass par défaut, manifests Kubeflow v1.9 clonés. Pré-requis pour l'installation satisfaits."),
    hr(),

    // K8s TP5
    h2("TP K8s 5 — Installation complète de Kubeflow"),
    h3("Objectif"),
    p("Déployer l'intégralité de la plateforme Kubeflow (Istio, cert-manager, Dex, Dashboard, Notebooks, Pipelines, KServe, Katib, Training Operator)."),
    code("$ cd ~/manifests"),
    code("$ while ! kustomize build example | kubectl apply -f -; do"),
    code("    echo 'Retrying to apply resources...'"),
    code("    sleep 10"),
    code("  done"),
    code(""),
    code("# Suivi dans un second terminal"),
    code("$ watch -n 5 \"kubectl get pods -A | grep -v Running | grep -v Completed\""),
    h3("Phases de l'installation"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2400, 3200, 3426],
      rows: [
        new TableRow({ children: [headerCell("Phase", "2E4057", 2400), headerCell("Durée", "2E4057", 3200), headerCell("Composants", "2E4057", 3426)] }),
        new TableRow({ children: [cell("1 — CRDs & namespaces", "F0F0F0", 2400), cell("Premières secondes", "FFFFFF", 3200), cell("Custom Resource Definitions, namespaces de base", "FFFFFF", 3426)] }),
        new TableRow({ children: [cell("2 — Infrastructure", "F0F0F0", 2400), cell("1-5 min", "FFFFFF", 3200), cell("Istio, cert-manager, Dex, OIDC AuthService", "FFFFFF", 3426)] }),
        new TableRow({ children: [cell("3 — Composants KF", "F0F0F0", 2400), cell("5-15 min", "FFFFFF", 3200), cell("Dashboard, Notebooks, Pipelines, KServe, Katib", "FFFFFF", 3426)] }),
        new TableRow({ children: [cell("4 — Stabilisation", "F0F0F0", 2400), cell("15-20 min", "FFFFFF", 3200), cell("Readiness probes, health checks finaux", "FFFFFF", 3426)] }),
      ]
    }),
    p("Note : La boucle while permet de gérer les dépendances entre CRDs qui doivent être créées avant les ressources qui les utilisent. Les erreurs temporaires des premières itérations sont normales et attendues."),
    hr(),

    // K8s TP6
    h2("TP K8s 6 — Observation du déploiement"),
    h3("Namespaces créés par Kubeflow"),
    code("$ kubectl get ns"),
    code("NAME                   STATUS  AGE"),
    code("auth                   Active  8m"),
    code("cert-manager           Active  10m"),
    code("default                Active  2d"),
    code("istio-system           Active  10m"),
    code("knative-eventing       Active  6m"),
    code("knative-serving        Active  6m"),
    code("kube-node-lease        Active  2d"),
    code("kube-public            Active  2d"),
    code("kube-system            Active  2d"),
    code("kubeflow               Active  7m"),
    code("kubeflow-user-example  Active  5m"),
    code("local-path-storage     Active  25m"),
    h3("Pods dans le namespace kubeflow"),
    code("$ kubectl get pods -n kubeflow"),
    code("NAME                                             READY  STATUS"),
    code("centraldashboard-xxx                             2/2    Running"),
    code("jupyter-web-app-deployment-xxx                   2/2    Running"),
    code("katib-controller-xxx                             1/1    Running"),
    code("katib-db-manager-xxx                             1/1    Running"),
    code("katib-mysql-xxx                                  1/1    Running"),
    code("kserve-controller-manager-xxx                    2/2    Running"),
    code("ml-pipeline-xxx                                  2/2    Running"),
    code("ml-pipeline-ui-xxx                               2/2    Running"),
    code("notebook-controller-deployment-xxx               2/2    Running"),
    code("profiles-deployment-xxx                          3/3    Running"),
    code("training-operator-xxx                            1/1    Running"),
    code("volumes-web-app-deployment-xxx                   2/2    Running"),
    code(""),
    code("# Vérification globale : aucun Pod en erreur"),
    code("$ kubectl get pods -A --field-selector="),
    code("  status.phase!=Running,status.phase!=Succeeded"),
    code("(liste vide → tout fonctionne)"),
    hr(),

    // K8s TP7-10 condensed
    h2("TPs K8s 7, 8, 9, 10 — Vérification, Accès, Compréhension, Conservation"),
    h3("TP 7 — Vérification des composants essentiels"),
    code("$ kubectl get pods -n kubeflow -l app=centraldashboard"),
    code("NAME                        READY  STATUS"),
    code("centraldashboard-xxx-xxx    2/2    Running"),
    code(""),
    code("$ kubectl get pods -n istio-system"),
    code("NAME                               READY  STATUS"),
    code("istiod-xxx                         1/1    Running"),
    code("istio-ingressgateway-xxx           1/1    Running"),
    code(""),
    code("$ kubectl get pods -n auth"),
    code("NAME                            READY  STATUS"),
    code("dex-xxx                         1/1    Running"),
    code("oidc-authservice-xxx            1/1    Running"),
    code(""),
    code("$ kubectl get pods -n cert-manager"),
    code("NAME                         READY  STATUS"),
    code("cert-manager-xxx             1/1    Running"),
    code("cert-manager-cainjector-xxx  1/1    Running"),
    code("cert-manager-webhook-xxx     1/1    Running"),
    h3("TP 8 — Accès initial au dashboard Kubeflow"),
    code("# Port-forward depuis le master vers le dashboard"),
    code("$ kubectl port-forward svc/istio-ingressgateway -n istio-system \\"),
    code("  8080:80 --address=0.0.0.0 &"),
    code(""),
    code("# Connexion depuis le navigateur"),
    code("# URL : http://192.168.1.10:8080"),
    code("# Email : user@example.com"),
    code("# Password : 12341234"),
    code(""),
    code("# Changer le mot de passe par défaut"),
    code("$ kubectl get configmap dex-config -n auth -o yaml"),
    h3("TP 9 — Comprendre ce qui est installé"),
    code("$ kubectl get deployments -n kubeflow"),
    code("$ kubectl get services -n kubeflow"),
    code("$ kubectl get pvc -n kubeflow"),
    code(""),
    code("# Ressources consommées"),
    code("$ kubectl top nodes"),
    code("NAME          CPU(cores)  CPU%  MEMORY(bytes)  MEMORY%"),
    code("k8s-master    312m        7%    1.8Gi          23%"),
    code("k8s-worker1   2450m       40%   10.2Gi         63%"),
    code("k8s-worker2   1890m       31%   8.7Gi          54%"),
    h3("TP 10 — Conservation et nettoyage"),
    code("# Nettoyage complet (si nécessaire)"),
    code("$ cd ~/manifests"),
    code("$ kustomize build example | kubectl delete -f -"),
    code(""),
    code("# Ou nettoyage sélectif"),
    code("$ kubectl delete namespace kubeflow"),
    code("$ kubectl delete namespace istio-system"),
    code("$ kubectl delete namespace auth"),
    code("$ kubectl delete namespace cert-manager"),
    code("$ kubectl delete namespace knative-serving"),
    code("$ kubectl delete namespace knative-eventing"),

    pageBreak(),
    // ── DISTRIBUTED SYSTEMS SECTION ──────────────────────────────────────────
    h1("Séance 5 — Systèmes Distribués (TPs 5.1 à 5.3 + Lab Sécurité)"),
    p("Projet fil rouge : Système de Gestion Documentaire Distribué (SGDD) — système permettant à une organisation de stocker, rechercher et gérer des documents, supportant plusieurs centaines d'utilisateurs simultanés.", { italics: true }),
    hr(),

    // TP5.1
    h2("TP 5.1 — Schématisation de l'architecture distribuée (30 min)"),
    h3("Architecture logique — Composants identifiés"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2400, 3600, 3026],
      rows: [
        new TableRow({ children: [headerCell("Service", "2E4057", 2400), headerCell("Responsabilité", "2E4057", 3600), headerCell("Technologie", "2E4057", 3026)] }),
        new TableRow({ children: [cell("API Gateway", "F4F4F4", 2400), cell("Point d'entrée unique, routage, rate limiting, validation tokens JWT, terminaison TLS", "FFFFFF", 3600), cell("Nginx / Traefik / Kong", "FFFFFF", 3026)] }),
        new TableRow({ children: [cell("Auth Service", "F4F4F4", 2400), cell("Authentification (login), émission et révocation de tokens JWT, gestion des rôles et permissions", "FFFFFF", 3600), cell("Python FastAPI + PostgreSQL (Users DB)", "FFFFFF", 3026)] }),
        new TableRow({ children: [cell("Stockage Service", "F4F4F4", 2400), cell("CRUD des documents : upload, download, suppression, gestion des métadonnées et versions", "FFFFFF", 3600), cell("Python + MinIO/S3 + MongoDB (Docs DB)", "FFFFFF", 3026)] }),
        new TableRow({ children: [cell("Recherche Service", "F4F4F4", 2400), cell("Indexation full-text des documents, recherche multicritère, ranking des résultats", "FFFFFF", 3600), cell("Python + Elasticsearch / Whoosh (Search Index)", "FFFFFF", 3026)] }),
        new TableRow({ children: [cell("Notification Service", "F4F4F4", 2400), cell("Alertes lors d'uploads, modifications, partages — envoi email/push", "FFFFFF", 3600), cell("Python + Redis Pub/Sub + SMTP", "FFFFFF", 3026)] }),
        new TableRow({ children: [cell("Cache Layer", "F4F4F4", 2400), cell("Cache des tokens JWT valides, cache des résultats de recherche fréquents, sessions", "FFFFFF", 3600), cell("Redis", "FFFFFF", 3026)] }),
      ]
    }),
    p(""),
    h3("Architecture logique — ASCII Art"),
    code("                    ┌─────────────────────────────┐"),
    code("     Internet  ────►│       API GATEWAY            │"),
    code("                    │ (routage, auth, rate limit,  │"),
    code("                    │  TLS termination, logging)   │"),
    code("                    └──┬───┬───┬───────┬──────────┘"),
    code("                       │   │   │       │"),
    code("          ┌────────────┘   │   │       └────────────┐"),
    code("          │                │   │                    │"),
    code("   ┌──────▼──────┐  ┌──────▼───────┐  ┌────────────▼──┐"),
    code("   │ Auth Service│  │Stockage Svc  │  │Recherche Svc  │"),
    code("   │ (JWT, rôles)│  │(CRUD, upload)│  │(indexation,   │"),
    code("   └──────┬──────┘  └──────┬───────┘  │ full-text)    │"),
    code("          │                │           └────────┬──────┘"),
    code("   ┌──────▼──────┐  ┌──────▼───────┐          │"),
    code("   │ Users DB    │  │  MongoDB     │  ┌────────▼──────┐"),
    code("   │ (PostgreSQL)│  │  + MinIO     │  │ Elasticsearch  │"),
    code("   └─────────────┘  └──────┬───────┘  └───────────────┘"),
    code("                           │"),
    code("              ┌────────────▼───────────────┐"),
    code("              │    Notification Service      │"),
    code("              │  (Redis Pub/Sub + SMTP)     │"),
    code("              └─────────────────────────────┘"),
    code(""),
    code("       ┌──────────────────────────────────────┐"),
    code("       │         Redis (Cache global)          │"),
    code("       │  tokens JWT + sessions + résultats   │"),
    code("       └──────────────────────────────────────┘"),
    p(""),
    h3("Flux d'interactions modélisés"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2400, 6626],
      rows: [
        new TableRow({ children: [headerCell("Opération", "2E4057", 2400), headerCell("Flux complet", "2E4057", 6626)] }),
        new TableRow({ children: [cell("Upload document", "F4F4F4", 2400), cell("Client → Gateway → Auth (vérifie JWT) → Stockage (sauvegarde fichier + métadonnées) → file Redis → Recherche (indexation async) → Notification (alerte email)", "FFFFFF", 6626)] }),
        new TableRow({ children: [cell("Download document", "F4F4F4", 2400), cell("Client → Gateway → Auth (vérifie JWT + droits lecture) → Cache Redis (si cache hit) OU Stockage (récupération) → Client", "FFFFFF", 6626)] }),
        new TableRow({ children: [cell("Recherche", "F4F4F4", 2400), cell("Client → Gateway → Auth → Cache Redis (si résultat en cache) OU Recherche (query Elasticsearch) → tri résultats → Client", "FFFFFF", 6626)] }),
      ]
    }),
    p(""),
    h3("Architecture physique — Déploiement"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2600, 3226, 3200],
      rows: [
        new TableRow({ children: [headerCell("Machine / Conteneur", "2E4057", 2600), headerCell("Services co-localisés", "2E4057", 3226), headerCell("Justification", "2E4057", 3200)] }),
        new TableRow({ children: [cell("VM-1 (API Layer)", "F4F4F4", 2600), cell("API Gateway + Auth Service (2 instances)", "FFFFFF", 3226), cell("Point d'entrée — réseau exposé. Auth repliqué pour haute disponibilité.", "FFFFFF", 3200)] }),
        new TableRow({ children: [cell("VM-2 (Business)", "F4F4F4", 2600), cell("Stockage Service + Notification Service", "FFFFFF", 3226), cell("Traitement métier principal. Stockage accède à MinIO et MongoDB.", "FFFFFF", 3200)] }),
        new TableRow({ children: [cell("VM-3 (Search)", "F4F4F4", 2600), cell("Recherche Service + Elasticsearch", "FFFFFF", 3226), cell("Co-localisation pour réduire la latence d'indexation.", "FFFFFF", 3200)] }),
        new TableRow({ children: [cell("VM-4 (Data)", "F4F4F4", 2600), cell("PostgreSQL + MongoDB + MinIO", "FFFFFF", 3226), cell("Isolation des données persistantes. Réseau privé uniquement.", "FFFFFF", 3200)] }),
        new TableRow({ children: [cell("VM-5 (Cache)", "F4F4F4", 2600), cell("Redis (cache + pub/sub)", "FFFFFF", 3226), cell("Partagé entre tous les services. Haute disponibilité (Redis Sentinel).", "FFFFFF", 3200)] }),
      ]
    }),
    p(""),
    h3("Réponses aux questions du gabarit"),
    bullet("Nombre de services : 5 services logiques (Gateway, Auth, Stockage, Recherche, Notification) + 1 couche cache (Redis) + 3 bases de données dédiées."),
    bullet("Protocoles : HTTP/REST entre Gateway et services internes ; Redis Pub/Sub pour les notifications asynchrones ; potentiellement gRPC pour les communications Stockage→Recherche (haute performance)."),
    bullet("Bases de données : UNE par service (pattern database per service) — PostgreSQL pour Auth, MongoDB pour Stockage, Elasticsearch pour Recherche. Évite les dépendances entre services."),
    bullet("Appels parallélisables : lors d'un upload, l'indexation (Recherche) et la notification peuvent être déclenchées en parallèle après la confirmation de Stockage."),
    bullet("Chemin critique (upload) : Client → Gateway (auth + routing) → Auth (validation JWT) → Stockage (I/O fichier + MongoDB) = 3 hops. L'indexation est async (hors chemin critique). La latence totale perçue ≈ latence Auth + latence Stockage."),
    hr(),

    // TP5.2
    h2("TP 5.2 — Analyse des défis distribués (30 min)"),
    p("Grille d'analyse complète par composant du SGDD."),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [1800, 2000, 2400, 2826],
      rows: [
        new TableRow({ children: [headerCell("Composant", "2E4057", 1800), headerCell("Défi", "2E4057", 2000), headerCell("Risque concret", "2E4057", 2400), headerCell("Proposition de solution", "2E4057", 2826)] }),
        new TableRow({ children: [
          cell("Auth Service", "F4F4F4", 1800),
          cell("Disponibilité (SPOF critique)", "FCE8E8", 2000),
          cell("Si Auth tombe, personne ne peut se connecter → tout le SGDD est bloqué", "FCE8E8", 2400),
          cell("2 instances Auth avec load balancer. Cache Redis pour les tokens JWT valides : le Gateway peut valider les tokens même si Auth est temporairement indisponible.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Auth Service", "F4F4F4", 1800),
          cell("Cohérence des révocations JWT", "FFF8E1", 2000),
          cell("Un token JWT révoqué (déconnexion) peut rester valide jusqu'à son expiration si le cache n'est pas invalidé", "FFF8E1", 2400),
          cell("Token TTL court (15 min). Liste noire des tokens révoqués dans Redis. Rotation automatique des clés de signature.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Stockage Service", "F4F4F4", 1800),
          cell("Cohérence entre fichier et index", "FCE8E8", 2000),
          cell("Un document uploadé mais pas encore indexé → invisible en recherche → utilisateur croit que l'upload a échoué", "FCE8E8", 2400),
          cell("File de messages Redis pour la synchronisation Stockage→Recherche. Réponse immédiate à l'utilisateur après sauvegarde + message 'indexation en cours'. Cohérence éventuelle acceptable.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Stockage Service", "F4F4F4", 1800),
          cell("Upload large (idempotence)", "FFF8E1", 2000),
          cell("Timeout réseau pendant upload → client rejoue la requête → doublon ou corruption", "FFF8E1", 2400),
          cell("Clé d'idempotence UUID par upload. Upload multipart pour les grands fichiers. Vérification checksum côté serveur.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Recherche Service", "F4F4F4", 1800),
          cell("Latence d'indexation", "FCE8E8", 2000),
          cell("L'indexation de gros documents PDF peut prendre 10-30s, bloquant le retour à l'utilisateur", "FCE8E8", 2400),
          cell("Indexation asynchrone via file Redis. Cache Elasticsearch des recherches fréquentes (TTL 5 min). Résultat partiel avec pagination.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Recherche Service", "F4F4F4", 1800),
          cell("Disponibilité si Elasticsearch tombe", "FFF8E1", 2000),
          cell("La recherche full-text devient indisponible alors que upload/download peuvent continuer", "FFF8E1", 2400),
          cell("Fallback : retourner un message 'Recherche temporairement indisponible' mais permettre la navigation par répertoire. Circuit breaker vers Elasticsearch.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("API Gateway", "F4F4F4", 1800),
          cell("Scalabilité (pics de charge)", "FCE8E8", 2000),
          cell("Pic d'uploads simultanés (fin de journée, deadline) → surcharge du Gateway", "FCE8E8", 2400),
          cell("Auto-scaling horizontal (Kubernetes HPA). Rate limiting par utilisateur (ex: 100 req/min). File d'attente côté client pour les batches d'uploads.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Redis (Cache)", "F4F4F4", 1800),
          cell("Partition réseau (split brain)", "FFF8E1", 2000),
          cell("Redis Sentinel vote incorrectement → deux masters actifs → incohérences de cache", "FFF8E1", 2400),
          cell("Redis Sentinel (3 nœuds minimum pour quorum). Délai de grâce avant failover. TTL courts pour limiter l'impact d'un split brain.", "E8F5E9", 2826)
        ]}),
        new TableRow({ children: [
          cell("Notification Service", "F4F4F4", 1800),
          cell("Couplage temporel", "FFF8E1", 2000),
          cell("Si le service email externe (SMTP) est lent, toute la chaîne d'upload est bloquée", "FFF8E1", 2400),
          cell("Communication via Redis Pub/Sub : découplage total. Stockage → file → Notification traite de manière asynchrone. Pas d'impact sur la latence de l'upload.", "E8F5E9", 2826)
        ]}),
      ]
    }),
    p(""),
    h3("Patterns appliqués et leurs trade-offs"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2000, 2600, 2200, 2226],
      rows: [
        new TableRow({ children: [headerCell("Pattern", "1A6B5A", 2000), headerCell("Problème résolu", "1A6B5A", 2600), headerCell("Avantage", "1A6B5A", 2200), headerCell("Trade-off", "1A6B5A", 2226)] }),
        new TableRow({ children: [cell("Cache Redis", "F0F7F4", 2000), cell("Latence + charge DB Auth", "FFFFFF", 2600), cell("Réponse en <1ms pour tokens valides", "FFFFFF", 2200), cell("Invalidation complexe si token révoqué", "FFFFFF", 2226)] }),
        new TableRow({ children: [cell("Réplication Auth (x2)", "F0F7F4", 2000), cell("Disponibilité (SPOF)", "FFFFFF", 2600), cell("Failover automatique", "FFFFFF", 2200), cell("Cohérence sessions (besoin sticky ou Redis)", "FFFFFF", 2226)] }),
        new TableRow({ children: [cell("File Redis (Pub/Sub)", "F0F7F4", 2000), cell("Couplage Stockage↔Recherche", "FFFFFF", 2600), cell("Notifications et indexation async", "FFFFFF", 2200), cell("Délai de traitement (cohérence éventuelle)", "FFFFFF", 2226)] }),
        new TableRow({ children: [cell("Circuit Breaker", "F0F7F4", 2000), cell("Cascade pannes (Elasticsearch)", "FFFFFF", 2600), cell("Protège les autres services", "FFFFFF", 2200), cell("Dégradation de fonctionnalité visible", "FFFFFF", 2226)] }),
        new TableRow({ children: [cell("Idempotency Key", "F0F7F4", 2000), cell("Doublons sur retry d'upload", "FFFFFF", 2600), cell("Sécurité des reprises réseau", "FFFFFF", 2200), cell("Stockage supplémentaire des clés (TTL)", "FFFFFF", 2226)] }),
      ]
    }),
    hr(),

    // TP5.3
    h2("TP 5.3 — Cartographie des surfaces d'attaque (30 min)"),
    p("Matrice de sécurité complète pour l'architecture SGDD."),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [1900, 1800, 3326, 1000 + 1000 - 1000 + 900 - 900],
      rows: [
        new TableRow({ children: [
          headerCell("Surface d'attaque", "8B1A1A", 2000),
          headerCell("Menace principale", "8B1A1A", 2000),
          headerCell("Contrôles proposés", "8B1A1A", 3426),
          headerCell("Priorité", "8B1A1A", 1600),
        ]}),
        new TableRow({ children: [
          cell("API externe (Gateway)", "F4F4F4", 2000),
          cell("DDoS, injection (SQL/NoSQL/Command), brute force auth, OWASP Top 10", "FCE8E8", 2000),
          cell("Rate limiting (100 req/min/user), WAF Cloudflare/ModSecurity, validation stricte de toutes les entrées, lockout après 5 échecs, HTTPS obligatoire (TLS 1.3)", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
        new TableRow({ children: [
          cell("Communications inter-services (Auth↔Stockage, etc.)", "F4F4F4", 2000),
          cell("MITM, usurpation d'identité de service, écoute passive du trafic interne", "FCE8E8", 2000),
          cell("mTLS entre TOUS les services (certificats mutuels). Vérification de l'audience JWT (claim aud). Pas de communication en clair même en réseau interne.", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
        new TableRow({ children: [
          cell("Base de données PostgreSQL (Users)", "F4F4F4", 2000),
          cell("SQL injection, accès non autorisé, vol de credentials, dump de données", "FCE8E8", 2000),
          cell("Requêtes paramétrées uniquement (ORM). Credentials dans HashiCorp Vault. Réseau privé isolé (pas d'accès direct depuis Internet). Chiffrement des colonnes sensibles (bcrypt pour mots de passe).", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
        new TableRow({ children: [
          cell("MongoDB (Docs) + MinIO (Fichiers)", "F4F4F4", 2000),
          cell("Accès non autorisé, exfiltration de documents confidentiels, ransomware", "FCE8E8", 2000),
          cell("Authentification MongoDB activée (désactivée par défaut!). Chiffrement au repos. Segmentation réseau (sous-réseau privé DB). Backups chiffrés réguliers. Monitoring des accès anormaux.", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
        new TableRow({ children: [
          cell("Secrets et configuration (clés API, mots de passe, certificats)", "F4F4F4", 2000),
          cell("Fuite dans le code source (Git), variables d'env en clair, secrets dans les logs", "FCE8E8", 2000),
          cell("HashiCorp Vault pour tous les secrets. git-secrets / trufflehog en pre-commit. Rotation automatique (30 jours). Jamais de secrets en dur dans le code ou les variables Docker.", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
        new TableRow({ children: [
          cell("Interface d'administration (monitoring, déploiement, Kibana)", "F4F4F4", 2000),
          cell("Accès non autorisé au plan de contrôle, élévation de privilèges admin", "FCE8E8", 2000),
          cell("VPN obligatoire pour accès admin. MFA (TOTP) pour tous les comptes admin. RBAC granulaire (séparation ops/dev/admin). Audit trail de toutes les actions admin.", "FFFFFF", 3426),
          cell("🟠 Élevée", "FFF8E1", 1600),
        ]}),
        new TableRow({ children: [
          cell("Logs et traces (centralisés)", "F4F4F4", 2000),
          cell("Fuite de données sensibles (tokens JWT, PII, mots de passe) dans les logs", "FCE8E8", 2000),
          cell("Masquage automatique des PII (nom, email, CNIE). Jamais de tokens complets dans les logs (tronquer à 8 chars). Accès restreint aux logs (RBAC). Chiffrement du stockage des logs.", "FFFFFF", 3426),
          cell("🟠 Élevée", "FFF8E1", 1600),
        ]}),
        new TableRow({ children: [
          cell("Dépendances Python (pip, requirements.txt)", "F4F4F4", 2000),
          cell("Supply chain attack (paquet malveillant type PyPI), typosquatting, backdoor via dépendance compromise", "FCE8E8", 2000),
          cell("pip-audit en CI/CD. Lock files (requirements.txt avec hashes). SBOM généré à chaque build. Revue obligatoire des mises à jour de dépendances. Registry privé (Artifactory) pour éviter le typosquatting.", "FFFFFF", 3426),
          cell("🟡 Moyenne", "E8F5E9", 1600),
        ]}),
        new TableRow({ children: [
          cell("Redis (Pub/Sub + Cache)", "F4F4F4", 2000),
          cell("Injection de messages malveillants, accès non autorisé au cache (tokens)", "FCE8E8", 2000),
          cell("Authentification Redis (requirepass). TLS pour les connexions Redis. Réseau privé. TTL courts sur les données sensibles. Validation des messages côté consommateur.", "FFFFFF", 3426),
          cell("🟡 Moyenne", "E8F5E9", 1600),
        ]}),
        new TableRow({ children: [
          cell("Upload de fichiers (documents utilisateurs)", "F4F4F4", 2000),
          cell("Upload de fichiers malveillants (malware, scripts), déni de service par fichiers énormes, SSRF via fichiers SVG/HTML", "FCE8E8", 2000),
          cell("Limite de taille stricte (50 Mo max). Validation du type MIME (whitelist: PDF, DOCX, PNG, JPEG uniquement). Scan antivirus (ClamAV) avant stockage. Stockage dans un bucket isolé (jamais exécutable).", "FFFFFF", 3426),
          cell("🔴 Critique", "FCE8E8", 1600),
        ]}),
      ]
    }),
    hr(),

    // Lab Sécu
    h2("Lab Sécurité — Threat Modeling STRIDE + Zero Trust Readiness"),
    h3("Méthode STRIDE appliquée au SGDD"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [1800, 2626, 2100, 2500],
      rows: [
        new TableRow({ children: [headerCell("Catégorie STRIDE", "8B1A1A", 1800), headerCell("Menace SGDD", "8B1A1A", 2626), headerCell("Impact", "8B1A1A", 2100), headerCell("Contre-mesure", "8B1A1A", 2500)] }),
        new TableRow({ children: [cell("Spoofing (Usurpation)", "F4F4F4", 1800), cell("Fabrication d'un faux JWT signé (si clé de signature compromise) pour accéder aux documents d'autres utilisateurs", "FCE8E8", 2626), cell("Accès non autorisé aux documents confidentiels, violation RGPD", "FFFFFF", 2100), cell("JWT RS256 (clé asymétrique). Rotation des clés (30 jours). mTLS pour les services internes. Vérification de l'audience (claim aud).", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Tampering (Altération)", "F4F4F4", 1800), cell("Modification d'un document pendant le transfert inter-services (entre Stockage et Recherche)", "FFF8E1", 2626), cell("Corruption des données indexées, documents altérés sans détection", "FFFFFF", 2100), cell("mTLS sur toutes les communications internes. Checksum (SHA-256) des documents vérifié à chaque lecture. Signatures numériques pour les documents sensibles.", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Repudiation (Déni)", "F4F4F4", 1800), cell("Un utilisateur supprime un document confidentiel et nie l'avoir fait (absence de logs ou logs falsifiés)", "FFF8E1", 2626), cell("Litige légal impossible à résoudre, non-conformité RGPD", "FFFFFF", 2100), cell("Logs immuables (append-only, stockés hors portée des utilisateurs). Audit trail cryptographiquement signé pour toutes les opérations destructives.", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Information Disclosure (Fuite)", "F4F4F4", 1800), cell("Tokens JWT en clair dans les logs d'application ou messages d'erreur détaillés exposant la structure interne", "FCE8E8", 2626), cell("Vol de sessions, compromission de comptes utilisateurs", "FFFFFF", 2100), cell("Masquage des tokens dans les logs. Erreurs génériques en production (pas de stack trace). HTTPS partout. Audit régulier des logs pour détecter les fuites.", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Denial of Service", "F4F4F4", 1800), cell("DDoS sur l'API Gateway ou upload de milliers de fichiers PDF de 50 Mo simultanément pour saturer le stockage", "FCE8E8", 2626), cell("Indisponibilité totale du SGDD, perte de chiffre d'affaires ou blocage d'un service critique", "FFFFFF", 2100), cell("Rate limiting (Gateway + services). Quotas par utilisateur (50 uploads/jour, 5 Go/mois). Auto-scaling K8s. CDN avec protection DDoS. File d'attente pour les uploads lourds.", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Elevation of Privilege", "F4F4F4", 1800), cell("Un utilisateur modifie son token JWT (si non signé) pour changer son rôle de 'reader' à 'admin', ou exploite une IDOR pour accéder aux documents d'autres utilisateurs", "FCE8E8", 2626), cell("Accès à tous les documents, suppression ou exfiltration massive de données", "FFFFFF", 2100), cell("JWT avec signature RS256 non falsifiable. RBAC granulaire vérifié à chaque service (pas seulement au Gateway). Tests IDOR systématiques en CI/CD.", "E8F5E9", 2500)] }),
      ]
    }),
    p(""),
    h3("Checklist Zero Trust Readiness — Évaluation du SGDD"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [5426, 2000, 1600],
      rows: [
        new TableRow({ children: [headerCell("Principe Zero Trust", "2E4057", 5426), headerCell("Statut proposé", "2E4057", 2000), headerCell("Priorité", "2E4057", 1600)] }),
        new TableRow({ children: [cell("AuthN à chaque service (JWT vérifié à chaque hop, pas seulement au Gateway)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("AuthZ granulaire (permissions vérifiées par opération : lecture vs écriture vs suppression)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Moindre privilège (Recherche Service n'a accès qu'en lecture à l'index, pas à Stockage DB)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Chiffrement en transit (TLS 1.3 externe + mTLS entre services internes)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Chiffrement au repos (documents sensibles chiffrés en DB + MinIO AES-256)", "F4F4F4", 5426), yellowCell("⚠️ Partiel", 2000), cell("🟠 Élevée", "FFF8E1", 1600)] }),
        new TableRow({ children: [cell("Segmentation réseau (DBs dans sous-réseau privé, non exposées depuis Internet)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Logs d'audit (chaque accès document journalisé : user, action, timestamp, IP, document_id)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🟠 Élevée", "FFF8E1", 1600)] }),
        new TableRow({ children: [cell("Rotation des secrets (credentials DB et clés JWT rotés tous les 30 jours automatiquement)", "F4F4F4", 5426), yellowCell("⚠️ Prévu", 2000), cell("🟠 Élevée", "FFF8E1", 1600)] }),
        new TableRow({ children: [cell("Validation d'entrée (chaque service valide ses inputs : types, tailles, formats, whitelist)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Rate limiting (sur Gateway ET sur chaque service critique)", "F4F4F4", 5426), greenCell("✅ Implémenté", 2000), cell("🔴 Critique", "FCE8E8", 1600)] }),
        new TableRow({ children: [cell("Scan de dépendances (pip-audit dans CI/CD à chaque build)", "F4F4F4", 5426), yellowCell("⚠️ Prévu CI/CD", 2000), cell("🟡 Moyenne", "E8F5E9", 1600)] }),
        new TableRow({ children: [cell("Plan de réponse à incident (procédure documentée + RGPD 72h notification)", "F4F4F4", 5426), yellowCell("⚠️ À rédiger", 2000), cell("🟠 Élevée", "FFF8E1", 1600)] }),
      ]
    }),
    p(""),
    h3("Scénario : Compromission du service Stockage — Réponse"),
    new Table({
      width: { size: 9026, type: WidthType.DXA },
      columnWidths: [2200, 4326, 2500],
      rows: [
        new TableRow({ children: [headerCell("Phase", "8B1A1A", 2200), headerCell("Actions", "8B1A1A", 4326), headerCell("Objectif", "8B1A1A", 2500)] }),
        new TableRow({ children: [cell("Containment (immédiat)", "FCE8E8", 2200), cell("• Couper les règles réseau du service Stockage (Network Policy K8s)\n• Révoquer tous les tokens/credentials du service\n• Activer mode dégradé : Upload désactivé, Download depuis cache uniquement\n• Bloquer les appels vers/depuis Stockage au niveau service mesh", "FFFFFF", 4326), cell("Empêcher la propagation latérale de la compromission vers Auth DB et MongoDB", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Éradication (heures suivantes)", "FFF8E1", 2200), cell("• Analyser les logs : quand ? comment ? données accédées ?\n• Identifier la vulnérabilité (CVE ? injection ? RCE ?)\n• Scanner tous les autres services pour détecter une contamination\n• Vérifier l'intégrité des documents (hash comparison)", "FFFFFF", 4326), cell("Supprimer la cause racine et évaluer l'étendue des dégâts", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Recovery (rétablissement)", "E8F5E9", 2200), cell("• Redéployer Stockage Service depuis une image propre (jamais restaurer l'instance compromise)\n• Rotation IMMÉDIATE de tous les secrets : credentials MongoDB, clés JWT, certificats mTLS\n• Restaurer depuis backup chiffré si données corrompues\n• Réactiver progressivement avec surveillance renforcée 72h", "FFFFFF", 4326), cell("Remettre en état nominal de manière sûre et vérifiable", "E8F5E9", 2500)] }),
        new TableRow({ children: [cell("Post-mortem", "F4F4F4", 2200), cell("• Rédiger rapport d'incident (timeline, impact, actions)\n• Notifier les utilisateurs si données personnelles concernées (RGPD : 72h obligatoire)\n• Mettre à jour les procédures et règles de segmentation\n• Renforcer les alertes comportementales", "FFFFFF", 4326), cell("Apprendre de l'incident + conformité RGPD", "E8F5E9", 2500)] }),
      ]
    }),
    p(""),
    h3("Synthèse — 10 points clés retenus (Séance 5)"),
    bullet("Système distribué = plusieurs composants sur plusieurs machines, communicant par messages, apparaissant comme un système unique."),
    bullet("Absence d'horloge globale : les timestamps ne sont pas directement comparables entre nœuds → utiliser des horloges logiques de Lamport ou NTP."),
    bullet("Pannes partielles : un composant peut tomber sans que les autres le sachent → ambiguïté mort/lent/partition. Le circuit breaker gère ce cas."),
    bullet("CAP : en cas de partition réseau (inévitable), choisir entre cohérence et disponibilité. Pour le SGDD : documents bancaires → cohérence forte (CP) ; compteurs de vues → cohérence éventuelle (AP)."),
    bullet("Trois architectures : Client-Serveur (simple, SPOF), P2P (résilient, complexe), Microservices (flexible, coûteux en ops). SGDD = microservices."),
    bullet("Idempotence + Retry + Timeout : le trio indispensable. Sans eux, les pannes transitoires deviennent permanentes ou créent des doublons (double upload, double facturation)."),
    bullet("Surface d'attaque croît avec le nombre de services : chaque endpoint, chaque communication inter-service, chaque DB est un vecteur potentiel."),
    bullet("Zero Trust : aucun composant fiable par défaut, même interne. AuthN/AuthZ à chaque service, moindre privilège, chiffrement mTLS partout, vérification continue."),
    bullet("Patterns de résilience : cache, réplication, file de messages, circuit breaker, fallback — chacun résout un problème mais en introduit d'autres (trade-offs explicites)."),
    bullet("Sécurité by design : threat modeling STRIDE dès la phase de conception, pas en ajout tardif. Le coût de corriger en production est 10× plus élevé qu'en conception."),
  ]
};

// ── Build the document ────────────────────────────────────────────────────────
const doc = new Document({
  styles: {
    default: {
      document: { run: { font: "Arial", size: 22 } }
    },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: "2E4057" },
        paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: "1A6B5A" },
        paragraph: { spacing: { before: 280, after: 140 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 23, bold: true, font: "Arial", color: "444444" },
        paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 2 } },
    ]
  },
  numbering: {
    config: [
      {
        reference: "bullets",
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: "\u2022",
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } }
        }]
      }
    ]
  },
  sections: [coverSection, dockerSection]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync('/mnt/user-data/outputs/rapport-completion-tps.docx', buffer);
  console.log('✅ rapport-completion-tps.docx created successfully');
}).catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
